arena:
  pos1:
    world: event
    x: 16
    y: 19
    z: -252
  pos2:
    world: event
    x: -16
    y: -61
    z: -284
AnvilConfig:
  FinaleConfig:
    Name: Finale
    TimeVagueTick: 100
    TimeMultiVagueTick: 4
    TimeAfterTitle: 60
    Anvil:
      - [5,40]
      - [7,40]
      - [9,40]
      - [12,40]
      - [15,40]
      - [20,40]
      - [30,40]
      - [40,7]
      - [50,6]
      - [60,5]
      - [70,4]
      - [80,3]
      - [90,2]
      - [100,1]
  Config1:
    Name: MultiWave
    TimeVagueTick: 100
    TimeMultiVagueTick : 30
    TimeAfterTitle: 60
    Anvil:
      - [5,5]
      - [15,5]
      - [25,5]
      - [35,5]
      - [45,5]
      - [55,5]
      - [65,5]
      - [75,5]
      - [100,1]
  Config2:
    Name: ClassicShit
    TimeVagueTick: 100
    TimeMultiVagueTick : 40
    TimeAfterTitle: 60
    Anvil:
      - [25,1]
      - [35,1]
      - [45,1]
      - [55,1]
      - [65,1]
      - [35,2]
      - [75,1]
      - [40,2]
      - [85,1]
      - [88,1]
      - [90,1]
      - [50,2]
      - [92,1]
      - [94,1]
      - [96,1]
      - [97,1]
      - [98,1]
      - [99,1]
      - [70,2]
      - [100,1]
  Config3:
    Name: AnvilRain
    TimeVagueTick: 100
    TimeMultiVagueTick : 5
    TimeAfterTitle: 60
    Anvil:
      - [1,40]
      - [2,40]
      - [3,40]
      - [5,40]
      - [7,40]
      - [9,40]
      - [12,40]
      - [15,40]
      - [20,40]
      - [100,1]
  Config4:
    Name: NotUse
    TimeVagueTick: 100
    TimeMultiVagueTick : 60
    Anvil:
      - [25,1]
      - [35,1]
      - [45,1]
      - [55,1]
      - [65,1]
      - [35,2]
      - [75,1]
      - [40,2]
      - [85,1]
      - [88,1]
      - [90,1]
      - [50,2]
      - [92,1]
      - [94,1]
      - [96,1]
      - [97,1]
      - [98,1]
      - [99,1]
      - [70,2]
      - [100,1]
  Config5:
    Name: NotUse
    TimeVagueTick: 100
    TimeMultiVagueTick : 60
    Anvil:
      - [25,1]
      - [35,1]
      - [45,1]
      - [55,1]
      - [65,1]
      - [35,2]
      - [75,1]
      - [40,2]
      - [85,1]
      - [88,1]
      - [90,1]
      - [50,2]
      - [92,1]
      - [94,1]
      - [96,1]
      - [97,1]
      - [98,1]
      - [99,1]
      - [70,2]
      - [100,1]
  Config6:
    Name: NotUse
    TimeVagueTick: 100
    TimeMultiVagueTick : 60
    Anvil:
      - [25,1]
      - [35,1]
      - [45,1]
      - [55,1]
      - [65,1]
      - [35,2]
      - [75,1]
      - [40,2]
      - [85,1]
      - [88,1]
      - [90,1]
      - [50,2]
      - [92,1]
      - [94,1]
      - [96,1]
      - [97,1]
      - [98,1]
      - [99,1]
      - [70,2]
      - [100,1]
  Config7:
    Name: NotUse
    TimeVagueTick: 100
    TimeMultiVagueTick : 60
    Anvil:
      - [25,1]
      - [35,1]
      - [45,1]
      - [55,1]
      - [65,1]
      - [35,2]
      - [75,1]
      - [40,2]
      - [85,1]
      - [88,1]
      - [90,1]
      - [50,2]
      - [92,1]
      - [94,1]
      - [96,1]
      - [97,1]
      - [98,1]
      - [99,1]
      - [70,2]
      - [100,1]
  Config8:
    Name: NotUse
    TimeVagueTick: 100
    TimeMultiVagueTick : 60
    Anvil:
      - [25,1]
      - [35,1]
      - [45,1]
      - [55,1]
      - [65,1]
      - [35,2]
      - [75,1]
      - [40,2]
      - [85,1]
      - [88,1]
      - [90,1]
      - [50,2]
      - [92,1]
      - [94,1]
      - [96,1]
      - [97,1]
      - [98,1]
      - [99,1]
      - [70,2]
      - [100,1]
  Config9:
    Name: NotUse
    TimeVagueTick: 100
    TimeMultiVagueTick : 60
    Anvil:
      - [25,1]
      - [35,1]
      - [45,1]
      - [55,1]
      - [65,1]
      - [35,2]
      - [75,1]
      - [40,2]
      - [85,1]
      - [88,1]
      - [90,1]
      - [50,2]
      - [92,1]
      - [94,1]
      - [96,1]
      - [97,1]
      - [98,1]
      - [99,1]
      - [70,2]
      - [100,1]
  Config10:
    Name: NotUse
    Anvil:
      - [25,1]
      - [35,1]
      - [45,1]
      - [55,1]
      - [65,1]
      - [35,2]
      - [75,1]
      - [40,2]
      - [85,1]
      - [88,1]
      - [90,1]
      - [50,2]
      - [92,1]
      - [94,1]
      - [96,1]
      - [97,1]
      - [98,1]
      - [99,1]
      - [70,2]
      - [100,1]